### ISSUE TITLE
TODO-list

### ISSUE THREAD

**Issue by lws803** [lws803/Crime-detect#2]
- [x] Test out OpenPose detector
- [x] Knife detector SSD
- [x] Human detector SSD testing
- [x] Integration of knife and human detector and addition of optical flow algorithm
- [x] Integrate gun detector from https://github.com/sofwerx/gun-detection/tree/master/detect_pistol
- [x] Write GUI for the combined detectors using pyQT
- [x] Multi-thread GUI for detectors
- [x] Add touch ups and sounds to the GUI for good presentation

**Comment by aaryamNUS** [comment]
Initial testing with OpenPose done, skeletal tracking is working nicely

**Comment by aaryamNUS** [comment]
Training the knife detector to get a reliable model

**Comment by lws803** [comment]
Integrating the knife detector model and human detector with optical flow

**Comment by aaryamNUS** [comment]
Introduction of the gun detector and refinement of the knife detector complete

**Comment by marcus-pzj** [comment]
GUI up and running. 2 functional tabs.
